# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cGsWjaCVlM7E3FipY5IA4X4zrjUDrVB
"""

pip install streamlit-extras

#Package import
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import seaborn as sns
import numpy as np
from ipywidgets import interact, FloatSlider
import streamlit as st

from google.colab import drive
drive.mount('/content/drive')

## Data import
NPV = pd.read_excel('/content/drive/MyDrive/FIEP/FIEP NPV calculator.xlsx')

# Daten extrahieren
x_labels = NPV.iloc[3:15, 0]
startup_cashflows = NPV.iloc[3:15, 1]
cashcow_cashflows = NPV.iloc[3:15, 2]

# Funktion zur Diskontierung
def discount(cashflows, rate):
    return [cf / ((1 + rate) ** i) for i, cf in enumerate(cashflows)]

# Streamlit UI
st.title("Discounted Cash Flow Dashboard")

rate = st.slider("Wähle den Zinssatz (interest rate)", 0.01, 0.3, 0.1, step=0.01)

startup_discounted = discount(startup_cashflows, rate)
cashcow_discounted = discount(cashcow_cashflows, rate)

# Plot erstellen
fig, ax = plt.subplots(figsize=(10, 5))
x = range(len(x_labels))
bar_width = 0.35

ax.bar(x, startup_discounted, width=bar_width, label='Startup Discounted', color='lightblue')
ax.bar([i + bar_width for i in x], cashcow_discounted, width=bar_width, label='Cashcow Discounted', color='blue')

ax.set_xticks([i + bar_width / 2 for i in x])
ax.set_xticklabels(x_labels, rotation=45)
ax.set_ylabel("Discounted Values")
ax.set_title("Discounted Cash Flow")
ax.legend()
st.pyplot(fig)